### PR TITLE
Fix the Makefile

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by rec** [comment]
1. you should specify reviewers using the @ symbol and the reviewername!  (I'm away on vacation so not a good candidate...)
2. It's a shame that "-O0" is baked into the build - but I guess efficiency is simply never a concern for this...?

**Comment by sublimator** [comment]
Ah sorry, yeah, need to get into the habit.

@rec ;) While you're here...
@HowardHinnant 
@JoelKatz 

I just did the ~minimum to get this working a while back, and figured I'd push the commit, seeing this has been languishing in a state that doesn't `make` on a clean clone.

**Comment by sublimator** [comment]
@nbougalis What about the `"-O0"` ?

**Comment by sublimator** [comment]
Gah, killed your comment Nik, sorry

**Comment by nbougalis** [comment]
This patch is obviously fine. I plan on getting it pushed, along with a further refinement: 05329f4f41af3abc980a1b21dee7bd1545ec91c4

**Comment by nbougalis** [comment]
Merged as 6857c093611ecf912b0205b0c49ce93e906de825

**Pull request closed without merging**
